version: '3.8'

services:
  go-app:
    volumes:
      - ./.env:/app/.env
    container_name: go-app
    image: produit/go-app:1.0.1
    build: ./microservice-product
    environment:
     DATABASE_URL: "host=${DB_HOST} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - go_db
    restart: unless-stopped
  go_db:
    container_name: go_db
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql

    restart: unless-stopped

volumes:  
  pgdata: {}